apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-8bcz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-8bcz@sha256:76f9b909865e1378e74e392274946c669b457242aa56212963306aa54c82bf23
        name: my-nodejs
        resources: {}
status: {}
